---
# tasks file for beats

- include: check.yml

- block:
  - include: redhat.yml
    when: ansible_os_family == "RedHat"
  - include: debian.yml
    when: ansible_os_family == "Debian"
  when: beats_install

- include: config.yml

- name: Import predefined dashboards
  shell: /usr/share/metricbeat/scripts/import_dashboards -es https://{{beats_dashboard_output_host}}:{{beats_dashboard_output_port}}
